"""add holding purchase_date

Revision ID: 29324d6876c8
Revises: a9c6ccff1803
Create Date: 2026-03-16 17:26:58.558834
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '29324d6876c8'
down_revision: Union[str, None] = 'a9c6ccff1803'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('holdings', sa.Column('purchase_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('holdings', 'purchase_date')
    # ### end Alembic commands ###
