"""add binance credentials to user

Revision ID: fce1358ae00e
Revises: 29324d6876c8
Create Date: 2026-03-16 17:28:43.242768
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'fce1358ae00e'
down_revision: Union[str, None] = '29324d6876c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('binance_api_key', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('binance_api_secret', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('binance_last_synced', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'binance_last_synced')
    op.drop_column('users', 'binance_api_secret')
    op.drop_column('users', 'binance_api_key')
    # ### end Alembic commands ###
